
---
spring:

  config.activate.on-profile: default
#  sql:
#    init:
#      platform: h2
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1
    url: jdbc:postgresql://localhost:5432/conference_db
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml


cds:
  data-source:
    auto-config:
      enabled: false
  messaging:
    outbound:
      enabled: false
#  data:
#    sql:
#      names: plain
